version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-8"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 150
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
  - "**/node_modules/"
  - "**/*.test.jsx"
  - "**/*.test.js"
  - "**/*.stories.jsx"
  - "**/src/repositories/in-memory/*.js"